### ISSUE TITLE
1.18.2 Magma Server Crashing due to Puffish Skills (Crash log included)

### ISSUE THREAD

**Issue by xXDarkayTberXx** [pufmat/skillsmod#88]
Whenever I try to open the server with the mod inside, it crashes leaving this code at the beggining:

Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'boolean org.apache.commons.io.FileUtils.isEmptyDirectory(java.io.File)'
	at net.puffish.skillsmod.utils.PathUtils.isDirectoryEmpty(PathUtils.java:26) ~[puffish_skills-0.10.0-1.18.2-forge.jar%2390!/:?] {re:classloading}
	at net.puffish.skillsmod.SkillsMod.loadModConfig(SkillsMod.java:191) ~[puffish_skills-0.10.0-1.18.2-forge.jar%2390!/:?] {re:classloading}
	at net.puffish.skillsmod.SkillsMod$EventListener.onServerStarting(SkillsMod.java:608) ~[puffish_skills-0.10.0-1.18.2-forge.jar%2390!/:?] {re:classloading}
	at net.puffish.skillsmod.main.ForgeMain.onServerStarting(ForgeMain.java:73) ~[puffish_skills-0.10.0-1.18.2-forge.jar%2390!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:98) ~[forge-1.18.2-40.2.17-universal.jar%23107!/:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[server-1.18.2-20220404.173914-srg.jar%23102!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:934) ~[server-1.18.2-20220404.173914-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:288) ~[server-1.18.2-20220404.173914-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin}

If anyone knows about this I would thank you very much.

[crash-2024-04-28_14.31.23-server.txt](https://github.com/pufmat/skillsmod/files/15142180/crash-2024-04-28_14.31.23-server.txt)

**Comment by Tresillo2017** [comment]
```
at net.puffish.skillsmod.utils.PathUtils.isDirectoryEmpty(PathUtils.java:26) ~[puffish_skills-0.10.0-1.18.2-forge.jar%2390!/:?] {re:classloading}
```
Looks like the folder where the config is located isn't empty, try to delete it

**Comment by pufmat** [comment]
The libraries on the server are probably outdated. I think you should contact your server hosting provider.

**Comment by Tresillo2017** [comment]
I will try to update all mods on the server. Thanks you 

On May 1, 2024 10:40:49 PM GMT+02:00, Pufferfish ***@***.***> wrote:
>The libraries on the server are probably outdated. I think you should contact your server hosting provider.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pufmat/skillsmod/issues/88#issuecomment-2089097791
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

TomasPS
